title: "תשבצים בעברית"
description: "רשימת רמזי תשבץ בעברית"
language: he
direction: rtl
url: "https://edengby.github.io/my-crossword-site" # Update with your site URL

plugins:
  - jekyll-datapage_gen
  - jekyll-sitemap

# Data Page Generator Configuration
datapage_gen:
  datafiles:
    - crosswords
  template: 'crossword_template.html'
  name: 'name'
  dir: 'crosswords'
