title: "Crossword Clues"
description: "רשימת רמזים לתשחץ בעברית"
baseurl: ""
url: "https://YOUR-GITHUB-USERNAME.github.io"

# Include necessary plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Disqus configuration
disqus:
  shortname: YOUR-DISQUS-SHORTNAME
